# Site settings
title: Binarycodeworld
description: > # this means to ignore newlines until "baseurl:"
  Notes related to big data, machine learning...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://binarycodeworld.com" # the base hostname & protocol for your site
github_username:  jithinjustin
category-list: [Data Exploration, Test] # Build settings
markdown: kramdown
kramdown:
  input: GFM
